version: "3.7"
services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose --livereload
    ports:
      - 4003:4000
    volumes:
      - ./app:/srv/jekyll